apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cmdb.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmdb.labels" . | nindent 4 }}
data:
  settings.py: |+
    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    """
    Contact : 191715030@qq.com
    Author  : shenshuo
    Date    : 2019/4/15 14:59
    Desc    : 配置文件
    """

    import os

    from websdk2.consts import const

    ROOT_DIR = os.path.dirname(__file__)
    debug = True
    xsrf_cookies = False
    expire_seconds = 365 * 24 * 60 * 60
    cookie_secret = os.getenv('DEFAULT_COOKIE_SECRET', '{{ required "The cookieSecretPy is required" .Values.cookieSecretPy }}')

    DEFAULT_DB_DBHOST = os.getenv('DEFAULT_DB_DBHOST', '{{ required "The mysql.host is required" .Values.mysql.host }}')
    DEFAULT_DB_DBPORT = os.getenv('DEFAULT_DB_DBPORT', {{ required "The mysql.port is required" .Values.mysql.port }})
    DEFAULT_DB_DBUSER = os.getenv('DEFAULT_DB_DBUSER', '{{ required "The mysql.user is required" .Values.mysql.user }}')
    DEFAULT_DB_DBPWD = os.getenv('DEFAULT_DB_DBPWD', '{{ required "The mysql.passwd is required" .Values.mysql.passwd }}')
    DEFAULT_DB_DBNAME = os.getenv('DEFAULT_DB_DBNAME', '{{ required "The cmdbDB is required" .Values.cmdbDB }}')

    READONLY_DB_DBHOST = os.getenv('READONLY_DB_DBHOST', '{{ required "The mysql.host is required" .Values.mysql.host }}')
    READONLY_DB_DBPORT = os.getenv('READONLY_DB_DBPORT', {{ required "The mysql.port is required" .Values.mysql.port }})
    READONLY_DB_DBUSER = os.getenv('READONLY_DB_DBUSER', '{{ required "The mysql.user is required" .Values.mysql.user }}')
    READONLY_DB_DBPWD = os.getenv('READONLY_DB_DBPWD', '{{ required "The mysql.passwd is required" .Values.mysql.passwd }}')
    READONLY_DB_DBNAME = os.getenv('READONLY_DB_DBNAME', '{{ required "The cmdbDB is required" .Values.cmdbDB }}')

    DEFAULT_REDIS_HOST = os.getenv('DEFAULT_REDIS_HOST', '{{ required "The redis.host is required" .Values.redis.host }}')
    DEFAULT_REDIS_PORT = os.getenv('DEFAULT_REDIS_PORT', {{ required "The redis.port is required" .Values.redis.port }})
    DEFAULT_REDIS_DB = os.getenv('DEFAULT_REDIS_DB', {{ required "The adminv4RedisDB is required" .Values.adminv4RedisDB }})
    DEFAULT_REDIS_AUTH = os.getenv('DEFAULT_REDIS_AUTH', True)
    DEFAULT_REDIS_CHARSET = os.getenv('DEFAULT_REDIS_CHARSET', 'utf-8')
    DEFAULT_REDIS_PASSWORD = os.getenv('DEFAULT_REDIS_PASSWORD', '{{ required "The redis.passwd is required" .Values.redis.passwd }}')

    # consul 为Prometheus提供数据 选填
    DEFAULT_CONSUL_HOST = os.getenv('DEFAULT_CONSUL_HOST', '{{ required "The consul.host is required" .Values.consul.host }}')
    DEFAULT_CONSUL_PORT = os.getenv('DEFAULT_CONSUL_PORT', {{ required "The consul.port is required" .Values.consul.port }})
    DEFAULT_CONSUL_TOKEN = os.getenv('DEFAULT_CONSUL_TOKEN', '{{ .Values.consul.token }}')
    DEFAULT_CONSUL_SCHEME = os.getenv('DEFAULT_CONSUL_SCHEME', '{{ required "The consul.scheme is required" .Values.consul.scheme }}')

    # 和其他系统交互使用
    api_gw = "http://{{ template "gateway.innerApi" . }}"
    settings_auth_key = "{{ required "The gatewayInnerApiToken is required" .Values.gatewayInnerApiToken }}"

    # 资产变更通知webhook
    asset_change_notify = {}

    # JumpServer配置
    JMS_API_BASE_URL = os.getenv('JMS_API_BASE_URL', '{{ .Values.cmdbJmsApi.url }}')
    JMS_API_KEY_ID = os.getenv('JMS_API_KEY_ID', '{{ .Values.cmdbJmsApi.keyId }}')
    JMS_API_KEY_SECRET = os.getenv('JMS_API_KEY_SECRET', '{{ .Values.cmdbJmsApi.secret }}')
    
    try:
      from local_settings import *
    except ImportError:
      print('local_settings.py  No Found.')

    settings = dict(
      debug=debug,
      xsrf_cookies=xsrf_cookies,
      cookie_secret=cookie_secret,
      expire_seconds=expire_seconds,
      api_gw=api_gw,
      asset_change_notify=asset_change_notify,
      settings_auth_key=settings_auth_key,
      app_name='cmdb',
      databases={
        const.DEFAULT_DB_KEY: {
          const.DBHOST_KEY: DEFAULT_DB_DBHOST,
          const.DBPORT_KEY: DEFAULT_DB_DBPORT,
          const.DBUSER_KEY: DEFAULT_DB_DBUSER,
          const.DBPWD_KEY: DEFAULT_DB_DBPWD,
          const.DBNAME_KEY: DEFAULT_DB_DBNAME,
        },
        const.READONLY_DB_KEY: {
          const.DBHOST_KEY: READONLY_DB_DBHOST,
          const.DBPORT_KEY: READONLY_DB_DBPORT,
          const.DBUSER_KEY: READONLY_DB_DBUSER,
          const.DBPWD_KEY: READONLY_DB_DBPWD,
          const.DBNAME_KEY: READONLY_DB_DBNAME,
        }
      },
      redises={
        const.DEFAULT_RD_KEY: {
          const.RD_HOST_KEY: DEFAULT_REDIS_HOST,
          const.RD_PORT_KEY: DEFAULT_REDIS_PORT,
          const.RD_DB_KEY: DEFAULT_REDIS_DB,
          const.RD_AUTH_KEY: DEFAULT_REDIS_AUTH,
          const.RD_CHARSET_KEY: DEFAULT_REDIS_CHARSET,
          const.RD_PASSWORD_KEY: DEFAULT_REDIS_PASSWORD
        }
      },
      consuls={
        const.DEFAULT_CS_KEY: {
          const.CONSUL_HOST_KEY: DEFAULT_CONSUL_HOST,
          const.CONSUL_PORT_KEY: DEFAULT_CONSUL_PORT,
          const.CONSUL_TOKEN_KEY: DEFAULT_CONSUL_TOKEN,
          const.CONSUL_SCHEME_KEY: DEFAULT_CONSUL_SCHEME
        }
      },
      jmss={
        const.DEFAULT_JMS_KEY: {
          const.JMS_API_BASE_URL: JMS_API_BASE_URL,
          const.JMS_API_KEY_ID: JMS_API_KEY_ID,
          const.JMS_API_KEY_SECRET: JMS_API_KEY_SECRET
        }
      }
    )