apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cnmp.uname" . }}
  namespace: {{ required "The namespace is required" .Values.namespace }}
  labels:
    {{- include "cnmp.labels" . | nindent 4 }}
data:
  config.yaml: |+
    # 应用
    APP:
      NAME: "codo-cnmp" # 应用名称
      ENV: "PRD" # PRE/PRD/DEV 环境
      ADDR: "0.0.0.0:8000" # 监听地址
      TIMEOUT: 30  # 超时时间(秒)
      PROTOCOL: "HTTP" # HTTP/HTTPS
      VERSION: "v1.0.0" # 版本号
      SECRET: "{{ required "The cnmpSecret is required" .Values.cnmpSecret }}" # AES对称加密密钥

    # Websocket
    WS:
      ADDR: "0.0.0.0:8001"

    # 可观测
    OTEL:
      TRACE:
        ENDPOINT: ""  # 链路追踪地址
        INSECURE: TRUE # 是否开启安全连接
      METRIC:
        ENABLE_EXEMPLAR: TRUE # 是否开启指标采样
      LOG:
        LEVEL: DEBUG

    # Prometheus
    PROMETHEUS:
      ENABLED: true # 是否开启 Prometheus
      NETWORK: "tcp" # 网络类型
      ADDR: "0.0.0.0:8002" # 监听地址
      PATH: "/metrics" # 路径

    # 火焰图
    PPROF:
      ENABLE: true # 是否开启火焰图
      NETWORK: "tcp" #  网络类型
      ADDR: "0.0.0.0:8003" # 监听地址

    # 数据库
    DB:
      DB_TYPE: "mysql" # 数据库类型
      DB_USER: "{{ required "The mysql.user is required" .Values.mysql.user }}"
      DB_PASSWORD: "{{ required "The mysql.passwd is required" .Values.mysql.passwd }}"
      DB_HOST: "{{ required "The mysql.host is required" .Values.mysql.host }}"
      DB_NAME: "{{ required "The cnmpDB is required" .Values.cnmpDB }}"
      DB_TABLE_PREFIX: ""
      DB_FILE: ""
      DB_PORT: "{{ required "The mysql.port is required" .Values.mysql.port }}"
      DB_MaxIdleConns: 10
      DB_MaxOpenConns: 10
      DB_ConnMaxLifetime: 600 # (秒)
      DEBUG: true

    # Redis
    REDIS:
      R_HOST: {{ required "The redis.host is required" .Values.redis.host }}
      R_PORT: {{ required "The redis.port is required" .Values.redis.port }}
      R_PASSWORD: "{{ required "The redis.passwd is required" .Values.redis.passwd }}"
      R_DB: {{ required "The adminv4RedisDB is required" .Values.adminv4RedisDB }}

    TIANMEN:
      ADDR: "http://{{ template "gateway.innerApi" . }}"
      AUTH_KEY: "{{ required "The gatewayInnerApiToken is required" .Values.gatewayInnerApiToken }}"
      TIMEOUT: 10 # (秒)
