{{- if ne .Values.imagePullSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "imagepullsecret.uname" . }}
  namespace: {{ required "The namespace is required" .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
{{- end -}}