apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "flowCronjob.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flowCronjob.labels" . | nindent 4 }}
spec:
  replicas: {{ required "flowCronjobReplicas is required" .Values.flowCronjobReplicas }}
  selector:
    matchLabels:
      {{- include "flowCronjob.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flowCronjob.labels" . | nindent 8 }}
    spec:
      {{ include "imagepullsecret.define" . | nindent 6 }}
      containers:
      - image: {{ required "flowCronjobImage is required" .Values.flowCronjobImage }}
        name: {{ template "flowCronjob.uname" . }}-image
        imagePullPolicy: Always
        env:
        - name: SERVICE_NAME
          value: "cron-task"
        resources:
          limits:
            cpu: {{ required "flowCronjobCPULimit is required" .Values.flowCronjobCPULimit }}
            memory: {{ required "flowCronjobMemoryLimit is required" .Values.flowCronjobMemoryLimit }}
            ephemeral-storage: {{ required "flowCronjobEphemeralStorageLimit is required" .Values.flowCronjobEphemeralStorageLimit }}
          requests:
            cpu: {{ required "flowCronjobCPURequire is required" .Values.flowCronjobCPURequire }}
            memory: {{ required "flowCronjobMemoryRequire is required" .Values.flowCronjobMemoryRequire }}
            ephemeral-storage: {{ required "flowCronjobEphemeralStorageRequire is required" .Values.flowCronjobEphemeralStorageRequire }}
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: flow-conf
          mountPath: /data/settings.py
          subPath: settings.py
      volumes:
        - name: flow-conf
          configMap:
            name: {{ template "flowCronjob.uname" . }}

