
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cloud-agent-operator
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/part-of: cloud-agent-operator
    control-plane: controller-manager
  name: cloud-agent-operator-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager