---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-agent-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/part-of: cloud-agent-operator
  name: cloud-agent-operator-leader-election-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-agent-operator-manager-role
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - limitranges
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - codo.dev
    resources:
      - codocloudtasks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - codo.dev
    resources:
      - codocloudtasks/finalizers
    verbs:
      - update
  - apiGroups:
      - codo.dev
    resources:
      - codocloudtasks/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cloud-agent-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/part-of: cloud-agent-operator
  name: cloud-agent-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cloud-agent-operator
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/part-of: cloud-agent-operator
  name: cloud-agent-operator-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create