---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ include "label.common" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-agent-operator
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/part-of: cloud-agent-operator
  name: cloud-agent-operator-controller-manager
  namespace: {{ .Values.namespace }}