apiVersion: v1
kind: Service
metadata:
  name: {{ template "k2.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k2.labels" . | nindent 4}}
spec:
  selector:
    {{- include "k2.selectorLabels" . | nindent 4}}
  ports:
  - name: {{ template "k2.uname" . }}
    protocol: TCP
    port: {{ required "k2ListenPort is required" .Values.k2ListenPort }}
    targetPort: http