apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kerrigan.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kerrigan.labels" . | nindent 4 }}
data:
  settings.py: |+
    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    """
    Contact : 191715030@qq.com
    Author  : shenshuo
    Date    : 2019/1/21
    Desc    : 配置文件
    """

    import os
    from websdk2.consts import const

    ROOT_DIR = os.path.dirname(__file__)
    debug = True
    xsrf_cookies = True
    expire_seconds = 365 * 24 * 60 * 60
    cookie_secret = os.getenv('DEFAULT_COOKIE_SECRET', '{{ required "The cookieSecretPy is required" .Values.cookieSecretPy }}')

    DEFAULT_DB_DBHOST = os.getenv('DEFAULT_DB_DBHOST', '{{ required "The mysql.host is required" .Values.mysql.host }}')
    DEFAULT_DB_DBPORT = os.getenv('DEFAULT_DB_DBPORT', {{ required "The mysql.port is required" .Values.mysql.port }})
    DEFAULT_DB_DBUSER = os.getenv('DEFAULT_DB_DBUSER', '{{ required "The mysql.user is required" .Values.mysql.user }}')
    DEFAULT_DB_DBPWD = os.getenv('DEFAULT_DB_DBPWD', '{{ required "The mysql.passwd is required" .Values.mysql.passwd }}')
    DEFAULT_DB_DBNAME = os.getenv('DEFAULT_DB_DBNAME', '{{ required "The adminv4DB is required" .Values.adminv4DB }}')

    READONLY_DB_DBHOST = os.getenv('READONLY_DB_DBHOST', '{{ required "The mysql.host is required" .Values.mysql.host }}')
    READONLY_DB_DBPORT = os.getenv('READONLY_DB_DBPORT', {{ required "The mysql.port is required" .Values.mysql.port }})
    READONLY_DB_DBUSER = os.getenv('READONLY_DB_DBUSER', '{{ required "The mysql.user is required" .Values.mysql.user }}')
    READONLY_DB_DBPWD = os.getenv('READONLY_DB_DBPWD', '{{ required "The mysql.passwd is required" .Values.mysql.passwd }}')
    READONLY_DB_DBNAME = os.getenv('READONLY_DB_DBNAME', '{{ required "The adminv4DB is required" .Values.adminv4DB }}')



    try:
        from local_settings import *
    except ImportError:
        print('local_settings.py  No Found.')

    settings = dict(
        debug=debug,
        xsrf_cookies=xsrf_cookies,
        cookie_secret=cookie_secret,
        expire_seconds=expire_seconds,
        app_name='codo-kerrigan',
        databases={
            const.DEFAULT_DB_KEY: {
                const.DBHOST_KEY: DEFAULT_DB_DBHOST,
                const.DBPORT_KEY: DEFAULT_DB_DBPORT,
                const.DBUSER_KEY: DEFAULT_DB_DBUSER,
                const.DBPWD_KEY: DEFAULT_DB_DBPWD,
                const.DBNAME_KEY: DEFAULT_DB_DBNAME,
            },
            const.READONLY_DB_KEY: {
                const.DBHOST_KEY: READONLY_DB_DBHOST,
                const.DBPORT_KEY: READONLY_DB_DBPORT,
                const.DBUSER_KEY: READONLY_DB_DBUSER,
                const.DBPWD_KEY: READONLY_DB_DBPWD,
                const.DBNAME_KEY: READONLY_DB_DBNAME,
            }
        }
    )