apiVersion: v1
kind: Service
metadata:
  name: {{ template "kerrigan.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kerrigan.labels" . | nindent 4}}
spec:
  selector:
    {{- include "kerrigan.selectorLabels" . | nindent 4}}
  ports:
  - name: {{ template "kerrigan.uname" . }}
    protocol: TCP
    port: {{ required "kerriganListenPort is required" .Values.kerriganListenPort }}
    targetPort: http

