apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.uname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4}}
spec:
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4}}
  ports:
  - name: gateway-01
    protocol: TCP
    port: {{ required "gatewayListenPort is required" .Values.gatewayListenPort }}
    targetPort: gateway-01

    
