apiVersion: v1
kind: Service
metadata:
  name: {{ template "frontend.uname" . }}
  namespace: {{ required "The namesapce is required" .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4}}
spec:
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4}}
  ports:
  - name: {{ template "frontend.uname" . }}
    protocol: TCP
    port: {{ required "frontendListenPort is required" .Values.frontendListenPort }}
    targetPort: http

